---
AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - simple_contracts.gemspec
    - Gemfile
    - spec/**/*

Metrics/ClassLength:
  Max: 300

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/FormatString:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15
