version: '3.4'

services:
  web:
    environment:
      VIRTUAL_HOST: ${APP_HOST}
      VIRTUAL_PATH: '/'
      VIRTUAL_PORT: 3000

  webpack:
    environment:
      WEBPACKER_DEV_SERVER_PUBLIC: webpack.${APP_HOST}
      VIRTUAL_HOST: webpack.${APP_HOST}
      VIRTUAL_PATH: '/'
      VIRTUAL_PORT: 3035

  mail:
    environment:
      VIRTUAL_HOST: mail.${APP_HOST}
      VIRTUAL_PATH: '/'
      VIRTUAL_PORT: 1080
