name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.0', '3.1', '3.2', '3.3' ]
    env:
      RUBY_IMAGE: ${{ matrix.ruby }} # The image used in the Dockerfile
    name: Ruby ${{ matrix.ruby }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby w/ same version as image
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: |
          rake install
          dip provision
      - name: Run linters
        run: dip rubocop
      - name: Run tests
        run: dip rspec
  schema-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install dependencies
        run: npm install -g ajv-cli
      - name: Validate all dip.yml files
        run: find . -type f -name 'dip.yml' | grep -v '/invalid' | xargs -I {} ajv -s schema.json -d {}
